expect_that(1 ^ 1, equals(1))
expect_that(2 ^ 2, equals(4))

expect_that(2 + 2 == 4, is_true())
expect_that(2 == 1, is_false())

expect_that(1, is_a('numeric'))

expect_that(print('Hello World!'), prints_text('Hello World!'))

expect_that(log('a'), throws_error())

expect_that(config, is_a('list'))
expect_that(length(config), equals(4))
expect_that(config$db_conf, is_a('list'))
expect_that(config$firstFilter, is_a('list'))
expect_that(config$secondFilter, is_a('list'))
expect_that(config$tags, is_a('list'))
expect_that(config$db_conf$name, is_a('character'))
expect_that(config$db_conf$user, is_a('character'))
expect_that(config$db_conf$pass, is_a('character'))
expect_that(config$firstFilter$var, is_a('character'))
expect_that(config$firstFilter$spike_num, is_a('integer'))
expect_that(config$firstFilter$resp_num, is_a('integer'))
expect_that(config$secondFilter$time, is_a('numeric'))
expect_that(config$secondFilter$time[1]>=0,is_true())
expect_that(config$secondFilter$time[2]>config$secondFilter$time[1],is_true())
expect_that(config$secondFilter$time_step>0,is_true())
expect_that(config$secondFilter$time_step<(config$secondFilter$time[2]-config$secondFilter$time[1])/2 ,is_true())
expect_that(config$secondFilter$stage, is_a('character'))
expect_that(config$tags, is_a('list'))
expect_that(length(config$tags)>=1,is_true())
expect_that(length(config$tags[[1]])>=1,is_true())
expect_that(config$tags[[1]], is_a('character'))
